export function youtubeCard(id='abcdefghijk',title='Full video title',channel='Test Channel') {
  return `<yt-lockup-view-model><h3 title="${title}"><a class="ytLockupMetadataViewModelTitle" href="/watch?v=${id}&list=ignored">${title}</a></h3><yt-content-metadata-view-model><div class="ytContentMetadataViewModelMetadataRow"><span role="text">${channel}</span></div></yt-content-metadata-view-model><div class="ytLockupMetadataViewModelMenuButton"><button aria-label="More actions">⋮</button></div></yt-lockup-view-model>`;
}
export function youtubeFixture(watch=false) {
  return `<!doctype html><html lang="en"><head><style>body{font:14px Arial;margin:24px;color:#0f0f0f}yt-lockup-view-model{display:block;border:1px solid #ddd;padding:16px;margin:16px;width:320px}button{border:0;border-radius:20px;padding:8px 16px;font:500 14px/20px Arial;background:#eee;cursor:pointer}#top-level-buttons-computed{display:flex}ytd-menu-popup-renderer{display:block;position:fixed;top:200px;left:400px;background:white;border-radius:12px;box-shadow:0 4px 10px #0003;padding:8px 0}[role=menuitem]{display:flex;align-items:center;padding:8px 16px;font:400 14px/24px Arial;cursor:pointer;gap:16px}[role=menuitem] svg{width:24px;height:24px}ytd-watch-flexy,ytd-watch-metadata{display:block}</style></head><body>${watch?'<ytd-watch-flexy video-id="abcdefghijk"><div id="player"><h1>Advertisement title</h1></div><ytd-watch-metadata><h1><yt-formatted-string>Full video title</yt-formatted-string></h1><div id="owner"><div id="channel-name"><a href="/@test">Test Channel</a></div></div><div id="top-level-buttons-computed"><button aria-label="Share">Share</button><button>Download</button></div></ytd-watch-metadata></ytd-watch-flexy>':''}${youtubeCard()}${youtubeCard('lmnopqrstuv','Second video','Second Channel')}<script>
  document.addEventListener('click',event=>{if(event.target.closest('button[aria-label="More actions"]')){document.querySelector('ytd-menu-popup-renderer')?.remove();const menu=document.createElement('ytd-menu-popup-renderer');menu.setAttribute('role','menu');menu.innerHTML=['Add to queue','Share'].map(text=>'<div role="menuitem" tabindex="0"><svg viewBox="0 0 24 24"><path d="M2 2h20v20H2z"/></svg><span>'+text+'</span></div>').join('');document.body.append(menu);menu.querySelector('[role=menuitem]').focus();}});
  document.addEventListener('keydown',event=>{if(event.keyCode===27)document.querySelector('ytd-menu-popup-renderer')?.remove();});
  </script></body></html>`;
}
